apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
        - name: hello
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: hello


---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello
    tier: hello
  type: LoadBalancer